FILE_LINE_BREAK = '\n'
FILE_TAB = '  '
FILE_SEPARATOR = '---'
FILE_LOWRES_MAXSIZE = 4000000
LINK_SEPARATOR = ' | '
LINK_COMMA = ', '
HTML_LINE_BREAK = '<br/>\n'
HTML_TAB = '&nbsp&nbsp'
HTML_SEPARATOR = '<hr/>'
PUNCTUATION = ':,.?!/\\-_'
FACEBOOK = 'https://facebook.com/%s'
LINKEDIN = 'https://linkedin.com/in/%s'

SCHOLAR = 'https://scholar.google.com/citations?user=%s'
SCHOLAR_PHOTO_LOCAL = 'photos/%s_s.jpg'
WEBSITE_PHOTO_LOCAL = 'photos/%s_w.jpg'
LINKEDIN_PHOTO_LOCAL = 'photos/%s_l.jpg'
TWITTER_PHOTO_LOCAL = 'photos/%s_t.jpg'
FACEBOOK_PHOTO_LOCAL = 'photos/%s_f.jpg'

SCHOLAR_PHOTO_URL = 'https://scholar.google.com/citations?view_op=view_photo&user=%s'

TWITTER = 'https://twitter.com/%s'
VIMEO = 'https://vimeo.com/%s'
INSTAGRAM = 'https://www.instagram.com/%s'
GITHUB = 'https://github.com/%s'
YOUTUBE = 'https://youtube.com/channel/%s'
RESEARCH_GATE = 'https://researchgate.net/profile/%s'
MAILTO = 'mailto:%s'
GOOGLE_SEARCH = 'https://google.com/search?q=%s'
DEBUG_HTML_SCRIPT = '<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous"><link rel="stylesheet" href="debug.css"><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script><script src="debug.js"></script>'
